name: stagexl_flump
version: 0.3.2
author: Bernhard Pichler <support@stagexl.org>
description: The Flump runtime for the StageXL library.
homepage: http://www.stagexl.org
environment:
  sdk: '>=0.1.6 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.10.0 <0.11.0'
