name: stagexl_flump
version: 0.1.0
author: Bernhard Pichler <support@stagexl.org>
description: The Flump runtime for the StageXL library.
homepage: http://www.stagexl.org
dependencies:
  browser: any
  stagexl: any
